services:
  mongodb:
    image: mongo:7
    container_name: mongodb_sucursales
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: db_sucursales
    volumes:
      - mongo_data:/data/db

  sucursales-api:
    image: sucursales-api:1.0
    build: .
    container_name: sucursales_api
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/db_sucursales

volumes:
  mongo_data:
